version: '3.9'

services:

  frontend:
    build: ./frontend
    ports:
      - '8080:80'

  backend:
    build: ./backend
    ports:
      - '5000:80'
    environment:
      DB: "${DB}"
      PORT: 80
